[features]
seeds = false
skip-lint = false
[programs.localnet]
vaults = "5j3KuMK2u7KFtoEwiLTexUeooHq5NPQX96rYp5dhuze9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dhrumil/.config/solana/mainnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
